import Head from "next/head";
import { useState } from "react";
import CoordinatesPlane from "~/components/CoordinatesPlane";
import ThreeDPlane from "~/components/ThreeDPlane";

export default function Home() {
  const [is3D, setIs3D] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <nav className="container flex flex-col items-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Ware <span className="text-[hsl(280,100%,70%)]">3D</span> Logix
          </h1>
        </nav>
        <div className="flex flex-col items-center gap-5 px-4 ">
          <label className="relative inline-flex cursor-pointer items-center">
            <input
              type="checkbox"
              value=""
              className="peer sr-only"
              onChange={() => {
                setIs3D(!is3D);
              }}
            />
            <div className="peer h-6 w-11 rounded-full bg-gray-200 after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800"></div>
            <span className="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300">
              3D
            </span>
          </label>
          {is3D ? <ThreeDPlane /> : <CoordinatesPlane />}
        </div>
      </main>
    </>
  );
}
